### ISSUE TITLE
C

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#1]

**Comment by ScheiBig** [comment]
All of recognized tokens are styled. That being said, some tokens could be more discriminative (i.e. both `typedef` and `struct` types use same token; in some situations `*` used as pointer star also changes token type between build-in type (being same color as type that is pointed to), and normal operator - this is also seen in formatter having "_a stroke_" in such situations.

**Comment by ScheiBig** [comment]
Also `union`s are tokenized in a same way.
