### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#20]

**Comment by ScheiBig** [comment]
C# tokens are not 100% consistent, especially when mixing modifiers:
```csharp
class App
{
    static readonly string fld = "value"; // <= Only gets tokenized as static, not as readonly / constant-ish

}
```
or using modern features:
```csharp
public record Point(double x, double y); // Gets tokenized as class, not as record
```
Most likely this is due to some combination of language grammar being made for older version of language (before C# 9.0), and being tailored for simpler themes with few color/formatting combos.

**Comment by ScheiBig** [comment]
Tested and fixed token bugs, that are fixable (not a lot).
Current list of unfixable bugs:
- `readonly` fields are treated like normal fields, while `const` fields are treated as local static constants,
- non-struct records are styled properly on declaration, but as normal classes on usage,
- attributes should get decorator/annotation styling, but they are treated as classes; square brackets around them don't even get own token (they use `punctuation`),
- range operator (`..`) is not yet recognized by tokenizer - it will either be styled as `punctuation` (if you put spaces around it), or as illegal numerical constant (when next to numbers without spaces).

It is possible, that there are more bugs like ones above. It also should be noted, that unfortunately C# async functions aren't tokenized as `async` like in JS.

**Comment by ScheiBig** [comment]
> non-struct records are styled properly on declaration, but as normal classes on usage,
is no longer applicable, as such records have `recordClass` semantic token.
