### ISSUE TITLE
Regex (inline, JS/TS ?)

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#47]

**Comment by ScheiBig** [comment]
Styled all tokens, most of them according to intuition/what "_feels right_":
- OR `|` and NOT `^` are styled as keyword
- line anchors `^$` are styled as foreign syntax, mainly to make distinction between `^` meaning easier,
- character classes, both provided `[]` and build-in i.e. `\d`, `.` ar styled as types (implied by them being classes),
- quantity specifiers `*?+ {1,2}` are styled as numbers (implied by quantity),
- group delimiters are styled as functions (implied by them having side-effect of remembering found text),
- group back-refrences are styled as fields (implied by them being a "_state_" of search instance),
- group capture specifiers:
  - non-capturing `?:` operator is styled as comment (implied by its result not being important to flow),
  - look-behind `?!` operator is styled as label (implied by labels allowing to back-reference existing code),
  - look-ahead `?=` operator is styled as macro (implied by macros allowing to reference not-yet existing code).

Escape sequences for Regex special characters (like `\+`) get their coloring from general coloring scheme.
